services:
  postgres:
    image: postgres:18
    env_file:
      - portfolio_website/docker.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: -p 5432

  app:
    container_name: app_portfolio_website
    hostname: app_portfolio_website
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - portfolio_website/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      sh -c "if [ \"$$DEBUG\" = \"True\" ] || [ \"$$DEBUG\" = \"true\" ];
      then python manage.py runserver 0.0.0.0:8000;
      else gunicorn portfolio_website.wsgi:application --bind 0.0.0.0:8000; fi"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

volumes:
  postgres_data:
  static_data:
