# Generated by Django 4.2.2 on 2023-07-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='order',
        ),
    ]
