# Generated by Django 4.2.2 on 2023-07-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_experience_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title'),
        ),
    ]
