# Generated by Django 4.2.2 on 2023-07-05 21:35

from django.db import migrations, models
import portfolio_website.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=portfolio_website.custom_storage.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=portfolio_website.custom_storage.ImageSettingsStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
