# Generated by Django 4.2.2 on 2024-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_education_school_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show_percentage',
            field=models.BooleanField(default=True, verbose_name='Show Percentage'),
        ),
    ]
