# Generated by Django 4.2.2 on 2026-04-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_new_template_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='show_percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Category'),
        ),
    ]
