# Generated by Django 4.2.2 on 2023-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_generalsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='text_parameter',
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='link',
            field=models.CharField(blank=True, default='', verbose_name='Link'),
        ),
    ]
