# Generated by Codex on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactareainfo_delete_generalsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactAreaInfo',
        ),
    ]
