--
-- PostgreSQL database dump
--

\restrict ZHBnKIHMMil16fxihDW73YqC4lddhYwuF8BM26YeRt60mUbejgjjuT3HTIUUfNb

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact_message (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    name character varying(254) NOT NULL,
    email character varying(254) NOT NULL,
    subject character varying(254) NOT NULL,
    message text NOT NULL
);


ALTER TABLE public.contact_message OWNER TO postgres;

--
-- Name: contact_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_document (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    slug character varying(254) NOT NULL,
    button_text character varying(254) NOT NULL,
    file character varying(100) NOT NULL
);


ALTER TABLE public.core_document OWNER TO postgres;

--
-- Name: core_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_education (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    school_name character varying(254) NOT NULL,
    major character varying(254) NOT NULL,
    department character varying(254) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    school_location character varying(254) NOT NULL
);


ALTER TABLE public.core_education OWNER TO postgres;

--
-- Name: core_education_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_education ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_experience (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    company_name character varying(254) NOT NULL,
    job_title character varying(254) NOT NULL,
    job_location character varying(254) NOT NULL,
    start_date date NOT NULL,
    end_date date
);


ALTER TABLE public.core_experience OWNER TO postgres;

--
-- Name: core_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_experience ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_generalsetting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_generalsetting (
    id bigint CONSTRAINT core_generalsettings_id_not_null NOT NULL,
    name character varying(254) CONSTRAINT core_generalsettings_name_not_null NOT NULL,
    description character varying(254) CONSTRAINT core_generalsettings_description_not_null NOT NULL,
    updated_date timestamp with time zone CONSTRAINT core_generalsettings_updated_date_not_null NOT NULL,
    created_date timestamp with time zone CONSTRAINT core_generalsettings_created_date_not_null NOT NULL,
    parameter character varying(254) NOT NULL,
    text_parameter text NOT NULL
);


ALTER TABLE public.core_generalsetting OWNER TO postgres;

--
-- Name: core_generalsettings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_generalsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_generalsettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_imagesetting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_imagesetting (
    id bigint NOT NULL,
    name character varying(254) NOT NULL,
    description character varying(254) NOT NULL,
    file character varying(100) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    updated_date timestamp with time zone NOT NULL
);


ALTER TABLE public.core_imagesetting OWNER TO postgres;

--
-- Name: core_imagesetting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_imagesetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_imagesetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_sitepreference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_sitepreference (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    default_journey_tab character varying(20) NOT NULL
);


ALTER TABLE public.core_sitepreference OWNER TO postgres;

--
-- Name: core_sitepreference_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_sitepreference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_sitepreference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_skill (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    name character varying(254) NOT NULL,
    category character varying(254) NOT NULL
);


ALTER TABLE public.core_skill OWNER TO postgres;

--
-- Name: core_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_socialmedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_socialmedia (
    id bigint NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    name character varying(254) NOT NULL,
    link character varying(254) NOT NULL,
    icon character varying(254) NOT NULL
);


ALTER TABLE public.core_socialmedia OWNER TO postgres;

--
-- Name: core_socialmedia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_socialmedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_socialmedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: projects_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects_project (
    id bigint NOT NULL,
    title character varying(180) NOT NULL,
    slug character varying(200) NOT NULL,
    summary text NOT NULL,
    cover_image character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    tech_stack character varying(300) NOT NULL,
    is_featured boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    CONSTRAINT projects_project_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.projects_project OWNER TO postgres;

--
-- Name: projects_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_projectcategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects_projectcategory (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    icon character varying(80) NOT NULL
);


ALTER TABLE public.projects_projectcategory OWNER TO postgres;

--
-- Name: projects_projectcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects_projectcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_projectcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_projectimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects_projectimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    image_type character varying(20) NOT NULL,
    alt_text character varying(180) NOT NULL,
    caption character varying(220) NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT projects_projectimage_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.projects_projectimage OWNER TO postgres;

--
-- Name: projects_projectimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects_projectimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_projectimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_projectlink; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects_projectlink (
    id bigint NOT NULL,
    label character varying(80) NOT NULL,
    url character varying(200) NOT NULL,
    icon character varying(80) NOT NULL,
    is_primary boolean NOT NULL,
    "order" integer NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT projects_projectlink_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.projects_projectlink OWNER TO postgres;

--
-- Name: projects_projectlink_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects_projectlink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_projectlink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_projectsection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects_projectsection (
    id bigint NOT NULL,
    section_type character varying(30) NOT NULL,
    title character varying(160) NOT NULL,
    content text NOT NULL,
    data jsonb NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT projects_projectsection_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.projects_projectsection OWNER TO postgres;

--
-- Name: projects_projectsection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects_projectsection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_projectsection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add General Setting	7	add_generalsetting
26	Can change General Setting	7	change_generalsetting
27	Can delete General Setting	7	delete_generalsetting
28	Can view General Setting	7	view_generalsetting
29	Can add Image Setting	8	add_imagesetting
30	Can change Image Setting	8	change_imagesetting
31	Can delete Image Setting	8	delete_imagesetting
32	Can view Image Setting	8	view_imagesetting
33	Can add Skill	9	add_skill
34	Can change Skill	9	change_skill
35	Can delete Skill	9	delete_skill
36	Can view Skill	9	view_skill
37	Can add Experience	10	add_experience
38	Can change Experience	10	change_experience
39	Can delete Experience	10	delete_experience
40	Can view Experience	10	view_experience
41	Can add Education	11	add_education
42	Can change Education	11	change_education
43	Can delete Education	11	delete_education
44	Can view Education	11	view_education
45	Can add Social Media	12	add_socialmedia
46	Can change Social Media	12	change_socialmedia
47	Can delete Social Media	12	delete_socialmedia
48	Can view Social Media	12	view_socialmedia
49	Can add Document	13	add_document
50	Can change Document	13	change_document
51	Can delete Document	13	delete_document
52	Can view Document	13	view_document
53	Can add Site Preferences	14	add_sitepreference
54	Can change Site Preferences	14	change_sitepreference
55	Can delete Site Preferences	14	delete_sitepreference
56	Can view Site Preferences	14	view_sitepreference
57	Can add Message	15	add_message
58	Can change Message	15	change_message
59	Can delete Message	15	delete_message
60	Can view Message	15	view_message
61	Can add project	16	add_project
62	Can change project	16	change_project
63	Can delete project	16	delete_project
64	Can view project	16	view_project
65	Can add Project Category	17	add_projectcategory
66	Can change Project Category	17	change_projectcategory
67	Can delete Project Category	17	delete_projectcategory
68	Can view Project Category	17	view_projectcategory
69	Can add project section	18	add_projectsection
70	Can change project section	18	change_projectsection
71	Can delete project section	18	delete_projectsection
72	Can view project section	18	view_projectsection
73	Can add project link	19	add_projectlink
74	Can change project link	19	change_projectlink
75	Can delete project link	19	delete_projectlink
76	Can view project link	19	view_projectlink
77	Can add project image	20	add_projectimage
78	Can change project image	20	change_projectimage
79	Can delete project image	20	delete_projectimage
80	Can view project image	20	view_projectimage
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: contact_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact_message (id, updated_date, created_date, name, email, subject, message) FROM stdin;
\.


--
-- Data for Name: core_document; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_document (id, updated_date, created_date, "order", slug, button_text, file) FROM stdin;
\.


--
-- Data for Name: core_education; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_education (id, updated_date, created_date, school_name, major, department, start_date, end_date, school_location) FROM stdin;
\.


--
-- Data for Name: core_experience; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_experience (id, updated_date, created_date, company_name, job_title, job_location, start_date, end_date) FROM stdin;
\.


--
-- Data for Name: core_generalsetting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_generalsetting (id, name, description, updated_date, created_date, parameter, text_parameter) FROM stdin;
1	contact_error_message	New template key	2026-04-28 14:27:18.430793+00	2026-04-28 14:27:18.4308+00		
2	contact_form_email_placeholder	New template key	2026-04-28 14:27:18.430807+00	2026-04-28 14:27:18.430809+00		
3	contact_form_message_placeholder	New template key	2026-04-28 14:27:18.430814+00	2026-04-28 14:27:18.430816+00		
4	contact_form_name_placeholder	New template key	2026-04-28 14:27:18.430821+00	2026-04-28 14:27:18.430823+00		
5	contact_form_subject_placeholder	New template key	2026-04-28 14:27:18.430829+00	2026-04-28 14:27:18.430831+00		
6	contact_form_submit_label	New template key	2026-04-28 14:27:18.430836+00	2026-04-28 14:27:18.430838+00		
7	contact_heading	New template key	2026-04-28 14:27:18.430843+00	2026-04-28 14:27:18.430846+00		
8	contact_info_address_desc	New template key	2026-04-28 14:27:18.430851+00	2026-04-28 14:27:18.430853+00		
9	contact_info_address_title	New template key	2026-04-28 14:27:18.430858+00	2026-04-28 14:27:18.43086+00		
10	contact_info_email_desc	New template key	2026-04-28 14:27:18.430865+00	2026-04-28 14:27:18.430867+00		
11	contact_info_email_title	New template key	2026-04-28 14:27:18.430872+00	2026-04-28 14:27:18.430874+00		
12	contact_info_phone_desc	New template key	2026-04-28 14:27:18.430879+00	2026-04-28 14:27:18.430881+00		
13	contact_info_phone_title	New template key	2026-04-28 14:27:18.430886+00	2026-04-28 14:27:18.430888+00		
14	contact_page_title	New template key	2026-04-28 14:27:18.430893+00	2026-04-28 14:27:18.430895+00		
15	contact_subtitle	New template key	2026-04-28 14:27:18.4309+00	2026-04-28 14:27:18.430902+00		
16	contact_success_message	New template key	2026-04-28 14:27:18.430907+00	2026-04-28 14:27:18.430909+00		
17	home_about_heading	New template key	2026-04-28 14:27:18.430913+00	2026-04-28 14:27:18.430915+00		
18	home_about_paragraph_1	New template key	2026-04-28 14:27:18.430921+00	2026-04-28 14:27:18.430923+00		
19	home_about_paragraph_2	New template key	2026-04-28 14:27:18.430929+00	2026-04-28 14:27:18.430931+00		
20	home_about_subtitle	New template key	2026-04-28 14:27:18.430936+00	2026-04-28 14:27:18.430938+00		
21	home_featured_heading	New template key	2026-04-28 14:27:18.430943+00	2026-04-28 14:27:18.430945+00		
22	home_featured_project_1_desc	New template key	2026-04-28 14:27:18.430949+00	2026-04-28 14:27:18.430951+00		
23	home_featured_project_1_github_url	New template key	2026-04-28 14:27:18.430956+00	2026-04-28 14:27:18.430958+00		
24	home_featured_project_1_image_alt	New template key	2026-04-28 14:27:18.430963+00	2026-04-28 14:27:18.430965+00		
25	home_featured_project_1_image_url	New template key	2026-04-28 14:27:18.430978+00	2026-04-28 14:27:18.43098+00		
26	home_featured_project_1_tag	New template key	2026-04-28 14:27:18.430985+00	2026-04-28 14:27:18.430987+00		
27	home_featured_project_1_title	New template key	2026-04-28 14:27:18.430992+00	2026-04-28 14:27:18.430994+00		
28	home_featured_project_2_desc	New template key	2026-04-28 14:27:18.430999+00	2026-04-28 14:27:18.431001+00		
29	home_featured_project_2_github_url	New template key	2026-04-28 14:27:18.431006+00	2026-04-28 14:27:18.431008+00		
30	home_featured_project_2_image_alt	New template key	2026-04-28 14:27:18.431013+00	2026-04-28 14:27:18.431015+00		
31	home_featured_project_2_image_url	New template key	2026-04-28 14:27:18.43102+00	2026-04-28 14:27:18.431022+00		
32	home_featured_project_2_tag	New template key	2026-04-28 14:27:18.431027+00	2026-04-28 14:27:18.431029+00		
33	home_featured_project_2_title	New template key	2026-04-28 14:27:18.431034+00	2026-04-28 14:27:18.431036+00		
34	home_featured_project_3_desc	New template key	2026-04-28 14:27:18.431053+00	2026-04-28 14:27:18.431056+00		
35	home_featured_project_3_github_url	New template key	2026-04-28 14:27:18.431061+00	2026-04-28 14:27:18.431063+00		
36	home_featured_project_3_image_alt	New template key	2026-04-28 14:27:18.431069+00	2026-04-28 14:27:18.431071+00		
37	home_featured_project_3_image_url	New template key	2026-04-28 14:27:18.431076+00	2026-04-28 14:27:18.431078+00		
38	home_featured_project_3_tag	New template key	2026-04-28 14:27:18.431083+00	2026-04-28 14:27:18.431085+00		
39	home_featured_project_3_title	New template key	2026-04-28 14:27:18.43109+00	2026-04-28 14:27:18.431092+00		
40	home_featured_project_cta_github	New template key	2026-04-28 14:27:18.431097+00	2026-04-28 14:27:18.431099+00		
41	home_featured_project_cta_view	New template key	2026-04-28 14:27:18.431104+00	2026-04-28 14:27:18.431106+00		
42	home_featured_subtitle	New template key	2026-04-28 14:27:18.431111+00	2026-04-28 14:27:18.431113+00		
43	home_featured_view_all_label	New template key	2026-04-28 14:27:18.431118+00	2026-04-28 14:27:18.43112+00		
44	home_hero_contact_email	New template key	2026-04-28 14:27:18.431125+00	2026-04-28 14:27:18.431127+00		
45	home_hero_cta_contact_label	New template key	2026-04-28 14:27:18.431132+00	2026-04-28 14:27:18.431134+00		
46	home_hero_cta_contact_url	New template key	2026-04-28 14:27:18.431139+00	2026-04-28 14:27:18.431141+00		
47	home_hero_cta_github_label	New template key	2026-04-28 14:27:18.431146+00	2026-04-28 14:27:18.431148+00		
48	home_hero_cta_github_url	New template key	2026-04-28 14:27:18.431153+00	2026-04-28 14:27:18.431155+00		
49	home_hero_cta_linkedin_label	New template key	2026-04-28 14:27:18.43116+00	2026-04-28 14:27:18.431162+00		
50	home_hero_cta_linkedin_url	New template key	2026-04-28 14:27:18.431168+00	2026-04-28 14:27:18.431171+00		
51	home_hero_greeting	New template key	2026-04-28 14:27:18.431176+00	2026-04-28 14:27:18.431178+00		
52	home_hero_location	New template key	2026-04-28 14:27:18.431183+00	2026-04-28 14:27:18.431185+00		
53	home_hero_passion	New template key	2026-04-28 14:27:18.43119+00	2026-04-28 14:27:18.431192+00		
54	home_hero_profile_alt	New template key	2026-04-28 14:27:18.431198+00	2026-04-28 14:27:18.4312+00		
55	home_hero_role	New template key	2026-04-28 14:27:18.431205+00	2026-04-28 14:27:18.431207+00		
56	home_journey_edu_1_desc	New template key	2026-04-28 14:27:18.431212+00	2026-04-28 14:27:18.431214+00		
57	home_journey_edu_1_period	New template key	2026-04-28 14:27:18.431219+00	2026-04-28 14:27:18.431221+00		
58	home_journey_edu_1_school	New template key	2026-04-28 14:27:18.431233+00	2026-04-28 14:27:18.431235+00		
59	home_journey_edu_2_desc	New template key	2026-04-28 14:27:18.431241+00	2026-04-28 14:27:18.431243+00		
60	home_journey_edu_2_period	New template key	2026-04-28 14:27:18.431248+00	2026-04-28 14:27:18.43125+00		
61	home_journey_edu_2_school	New template key	2026-04-28 14:27:18.431255+00	2026-04-28 14:27:18.431257+00		
62	home_journey_exp_1_company	New template key	2026-04-28 14:27:18.431262+00	2026-04-28 14:27:18.431264+00		
63	home_journey_exp_1_desc	New template key	2026-04-28 14:27:18.431269+00	2026-04-28 14:27:18.431271+00		
64	home_journey_exp_1_period	New template key	2026-04-28 14:27:18.431276+00	2026-04-28 14:27:18.431278+00		
65	home_journey_exp_2_company	New template key	2026-04-28 14:27:18.431283+00	2026-04-28 14:27:18.431285+00		
66	home_journey_exp_2_desc	New template key	2026-04-28 14:27:18.43129+00	2026-04-28 14:27:18.431292+00		
67	home_journey_exp_2_period	New template key	2026-04-28 14:27:18.431297+00	2026-04-28 14:27:18.4313+00		
68	home_journey_heading	New template key	2026-04-28 14:27:18.431306+00	2026-04-28 14:27:18.431308+00		
69	home_journey_tab_education	New template key	2026-04-28 14:27:18.431313+00	2026-04-28 14:27:18.431315+00		
70	home_journey_tab_experience	New template key	2026-04-28 14:27:18.43132+00	2026-04-28 14:27:18.431322+00		
71	home_stack_heading	New template key	2026-04-28 14:27:18.431327+00	2026-04-28 14:27:18.431329+00		
72	home_stack_item_1	New template key	2026-04-28 14:27:18.431334+00	2026-04-28 14:27:18.431336+00		
73	home_stack_item_10	New template key	2026-04-28 14:27:18.431341+00	2026-04-28 14:27:18.431343+00		
74	home_stack_item_11	New template key	2026-04-28 14:27:18.431348+00	2026-04-28 14:27:18.43135+00		
75	home_stack_item_2	New template key	2026-04-28 14:27:18.431355+00	2026-04-28 14:27:18.431357+00		
76	home_stack_item_3	New template key	2026-04-28 14:27:18.431362+00	2026-04-28 14:27:18.431364+00		
77	home_stack_item_4	New template key	2026-04-28 14:27:18.431369+00	2026-04-28 14:27:18.431371+00		
78	home_stack_item_5	New template key	2026-04-28 14:27:18.431376+00	2026-04-28 14:27:18.431378+00		
79	home_stack_item_6	New template key	2026-04-28 14:27:18.431383+00	2026-04-28 14:27:18.431385+00		
80	home_stack_item_7	New template key	2026-04-28 14:27:18.43139+00	2026-04-28 14:27:18.431392+00		
81	home_stack_item_8	New template key	2026-04-28 14:27:18.431397+00	2026-04-28 14:27:18.431399+00		
82	home_stack_item_9	New template key	2026-04-28 14:27:18.431404+00	2026-04-28 14:27:18.431406+00		
83	project_all_projects_label	New template key	2026-04-28 14:27:18.431411+00	2026-04-28 14:27:18.431413+00		
84	project_apex_badge_1	New template key	2026-04-28 14:27:18.431419+00	2026-04-28 14:27:18.431421+00		
85	project_apex_badge_2	New template key	2026-04-28 14:27:18.431426+00	2026-04-28 14:27:18.431428+00		
86	project_apex_breadcrumb_label	New template key	2026-04-28 14:27:18.431433+00	2026-04-28 14:27:18.431435+00		
87	project_apex_feature_1	New template key	2026-04-28 14:27:18.43144+00	2026-04-28 14:27:18.431442+00		
88	project_apex_feature_2	New template key	2026-04-28 14:27:18.431447+00	2026-04-28 14:27:18.431449+00		
89	project_apex_feature_3	New template key	2026-04-28 14:27:18.431454+00	2026-04-28 14:27:18.431456+00		
90	project_apex_gallery_1_caption	New template key	2026-04-28 14:27:18.431461+00	2026-04-28 14:27:18.431463+00		
91	project_apex_gallery_1_image_alt	New template key	2026-04-28 14:27:18.431468+00	2026-04-28 14:27:18.43147+00		
92	project_apex_gallery_1_image_url	New template key	2026-04-28 14:27:18.431475+00	2026-04-28 14:27:18.431477+00		
93	project_apex_gallery_2_caption	New template key	2026-04-28 14:27:18.431482+00	2026-04-28 14:27:18.431484+00		
94	project_apex_gallery_2_image_alt	New template key	2026-04-28 14:27:18.431489+00	2026-04-28 14:27:18.431491+00		
95	project_apex_gallery_2_image_url	New template key	2026-04-28 14:27:18.431496+00	2026-04-28 14:27:18.431498+00		
96	project_apex_gallery_3_caption	New template key	2026-04-28 14:27:18.431503+00	2026-04-28 14:27:18.431505+00		
97	project_apex_gallery_3_image_alt	New template key	2026-04-28 14:27:18.43151+00	2026-04-28 14:27:18.431512+00		
98	project_apex_gallery_3_image_url	New template key	2026-04-28 14:27:18.431517+00	2026-04-28 14:27:18.431519+00		
99	project_apex_gallery_4_caption	New template key	2026-04-28 14:27:18.431524+00	2026-04-28 14:27:18.431526+00		
100	project_apex_gallery_4_image_alt	New template key	2026-04-28 14:27:18.431531+00	2026-04-28 14:27:18.431533+00		
101	project_apex_gallery_4_image_url	New template key	2026-04-28 14:27:18.431543+00	2026-04-28 14:27:18.431545+00		
102	project_apex_github_url	New template key	2026-04-28 14:27:18.43155+00	2026-04-28 14:27:18.431552+00		
103	project_apex_hero_desc	New template key	2026-04-28 14:27:18.431557+00	2026-04-28 14:27:18.431559+00		
104	project_apex_hero_title	New template key	2026-04-28 14:27:18.431564+00	2026-04-28 14:27:18.431566+00		
105	project_apex_live_demo_url	New template key	2026-04-28 14:27:18.431571+00	2026-04-28 14:27:18.431573+00		
106	project_apex_overview_text	New template key	2026-04-28 14:27:18.431578+00	2026-04-28 14:27:18.43158+00		
107	project_apex_page_title	New template key	2026-04-28 14:27:18.431585+00	2026-04-28 14:27:18.431587+00		
108	project_apex_stack_1	New template key	2026-04-28 14:27:18.431592+00	2026-04-28 14:27:18.431594+00		
109	project_apex_stack_2	New template key	2026-04-28 14:27:18.431599+00	2026-04-28 14:27:18.431601+00		
110	project_apex_stack_3	New template key	2026-04-28 14:27:18.431607+00	2026-04-28 14:27:18.431609+00		
111	project_apex_stack_4	New template key	2026-04-28 14:27:18.431614+00	2026-04-28 14:27:18.431616+00		
112	project_apex_stack_5	New template key	2026-04-28 14:27:18.431621+00	2026-04-28 14:27:18.431623+00		
113	project_apex_status_label	New template key	2026-04-28 14:27:18.431628+00	2026-04-28 14:27:18.43163+00		
114	project_apex_tech_desc	New template key	2026-04-28 14:27:18.431635+00	2026-04-28 14:27:18.431637+00		
115	project_apex_thumb_image_alt	New template key	2026-04-28 14:27:18.431642+00	2026-04-28 14:27:18.431644+00		
116	project_apex_thumb_image_url	New template key	2026-04-28 14:27:18.431649+00	2026-04-28 14:27:18.431651+00		
117	project_back_to_projects	New template key	2026-04-28 14:27:18.431656+00	2026-04-28 14:27:18.431658+00		
118	project_crypto_wallet_badge_1	New template key	2026-04-28 14:27:18.431675+00	2026-04-28 14:27:18.431677+00		
119	project_crypto_wallet_badge_2	New template key	2026-04-28 14:27:18.431682+00	2026-04-28 14:27:18.431684+00		
120	project_crypto_wallet_breadcrumb_label	New template key	2026-04-28 14:27:18.431689+00	2026-04-28 14:27:18.431691+00		
121	project_crypto_wallet_challenge_heading	New template key	2026-04-28 14:27:18.431697+00	2026-04-28 14:27:18.431699+00		
122	project_crypto_wallet_challenge_text	New template key	2026-04-28 14:27:18.431704+00	2026-04-28 14:27:18.431706+00		
123	project_crypto_wallet_cover_image_alt	New template key	2026-04-28 14:27:18.431711+00	2026-04-28 14:27:18.431713+00		
124	project_crypto_wallet_cover_image_url	New template key	2026-04-28 14:27:18.431718+00	2026-04-28 14:27:18.43172+00		
125	project_crypto_wallet_feature_1	New template key	2026-04-28 14:27:18.431725+00	2026-04-28 14:27:18.431727+00		
126	project_crypto_wallet_feature_2	New template key	2026-04-28 14:27:18.431732+00	2026-04-28 14:27:18.431734+00		
127	project_crypto_wallet_feature_3	New template key	2026-04-28 14:27:18.431739+00	2026-04-28 14:27:18.431741+00		
128	project_crypto_wallet_gallery_1_caption	New template key	2026-04-28 14:27:18.431746+00	2026-04-28 14:27:18.431748+00		
129	project_crypto_wallet_gallery_1_image_alt	New template key	2026-04-28 14:27:18.431753+00	2026-04-28 14:27:18.431755+00		
130	project_crypto_wallet_gallery_1_image_url	New template key	2026-04-28 14:27:18.431761+00	2026-04-28 14:27:18.431763+00		
131	project_crypto_wallet_gallery_2_caption	New template key	2026-04-28 14:27:18.431768+00	2026-04-28 14:27:18.43177+00		
132	project_crypto_wallet_gallery_2_image_alt	New template key	2026-04-28 14:27:18.431775+00	2026-04-28 14:27:18.431777+00		
133	project_crypto_wallet_gallery_2_image_url	New template key	2026-04-28 14:27:18.431782+00	2026-04-28 14:27:18.431784+00		
134	project_crypto_wallet_github_url	New template key	2026-04-28 14:27:18.431789+00	2026-04-28 14:27:18.431791+00		
135	project_crypto_wallet_hero_desc	New template key	2026-04-28 14:27:18.431796+00	2026-04-28 14:27:18.431798+00		
136	project_crypto_wallet_hero_title	New template key	2026-04-28 14:27:18.431802+00	2026-04-28 14:27:18.431805+00		
137	project_crypto_wallet_live_demo_url	New template key	2026-04-28 14:27:18.431813+00	2026-04-28 14:27:18.431815+00		
138	project_crypto_wallet_meta_duration_label	New template key	2026-04-28 14:27:18.43182+00	2026-04-28 14:27:18.431822+00		
139	project_crypto_wallet_meta_duration_value	New template key	2026-04-28 14:27:18.431827+00	2026-04-28 14:27:18.431829+00		
140	project_crypto_wallet_meta_outcome_label	New template key	2026-04-28 14:27:18.431834+00	2026-04-28 14:27:18.431836+00		
141	project_crypto_wallet_meta_outcome_value	New template key	2026-04-28 14:27:18.431841+00	2026-04-28 14:27:18.431843+00		
142	project_crypto_wallet_meta_role_label	New template key	2026-04-28 14:27:18.431848+00	2026-04-28 14:27:18.43185+00		
143	project_crypto_wallet_meta_role_value	New template key	2026-04-28 14:27:18.431855+00	2026-04-28 14:27:18.431857+00		
144	project_crypto_wallet_overview_text	New template key	2026-04-28 14:27:18.431862+00	2026-04-28 14:27:18.431864+00		
145	project_crypto_wallet_page_title	New template key	2026-04-28 14:27:18.431869+00	2026-04-28 14:27:18.431871+00		
146	project_crypto_wallet_solution_heading	New template key	2026-04-28 14:27:18.431876+00	2026-04-28 14:27:18.431878+00		
147	project_crypto_wallet_solution_point_1	New template key	2026-04-28 14:27:18.431883+00	2026-04-28 14:27:18.431885+00		
148	project_crypto_wallet_solution_point_2	New template key	2026-04-28 14:27:18.43189+00	2026-04-28 14:27:18.431892+00		
149	project_crypto_wallet_solution_point_3	New template key	2026-04-28 14:27:18.431897+00	2026-04-28 14:27:18.431899+00		
150	project_crypto_wallet_solution_text	New template key	2026-04-28 14:27:18.431904+00	2026-04-28 14:27:18.431906+00		
151	project_crypto_wallet_stack_1	New template key	2026-04-28 14:27:18.431911+00	2026-04-28 14:27:18.431914+00		
152	project_crypto_wallet_stack_2	New template key	2026-04-28 14:27:18.431919+00	2026-04-28 14:27:18.431922+00		
153	project_crypto_wallet_stack_3	New template key	2026-04-28 14:27:18.431927+00	2026-04-28 14:27:18.431929+00		
154	project_crypto_wallet_stack_4	New template key	2026-04-28 14:27:18.43194+00	2026-04-28 14:27:18.431942+00		
155	project_crypto_wallet_tech_desc	New template key	2026-04-28 14:27:18.431947+00	2026-04-28 14:27:18.431949+00		
156	project_devflow_badge_1	New template key	2026-04-28 14:27:18.431954+00	2026-04-28 14:27:18.431955+00		
157	project_devflow_badge_2	New template key	2026-04-28 14:27:18.43196+00	2026-04-28 14:27:18.431962+00		
158	project_devflow_breadcrumb_label	New template key	2026-04-28 14:27:18.431967+00	2026-04-28 14:27:18.431969+00		
159	project_devflow_feature_1	New template key	2026-04-28 14:27:18.431973+00	2026-04-28 14:27:18.431975+00		
160	project_devflow_feature_2	New template key	2026-04-28 14:27:18.43198+00	2026-04-28 14:27:18.431982+00		
161	project_devflow_feature_3	New template key	2026-04-28 14:27:18.431987+00	2026-04-28 14:27:18.431989+00		
162	project_devflow_gallery_1_caption	New template key	2026-04-28 14:27:18.431993+00	2026-04-28 14:27:18.431995+00		
163	project_devflow_gallery_1_image_alt	New template key	2026-04-28 14:27:18.432+00	2026-04-28 14:27:18.432002+00		
164	project_devflow_gallery_1_image_url	New template key	2026-04-28 14:27:18.432007+00	2026-04-28 14:27:18.432008+00		
165	project_devflow_gallery_2_caption	New template key	2026-04-28 14:27:18.432013+00	2026-04-28 14:27:18.432015+00		
166	project_devflow_gallery_2_image_alt	New template key	2026-04-28 14:27:18.43202+00	2026-04-28 14:27:18.432022+00		
167	project_devflow_gallery_2_image_url	New template key	2026-04-28 14:27:18.432026+00	2026-04-28 14:27:18.432028+00		
168	project_devflow_gallery_3_caption	New template key	2026-04-28 14:27:18.432033+00	2026-04-28 14:27:18.432035+00		
169	project_devflow_gallery_3_image_alt	New template key	2026-04-28 14:27:18.43204+00	2026-04-28 14:27:18.432042+00		
170	project_devflow_gallery_3_image_url	New template key	2026-04-28 14:27:18.432047+00	2026-04-28 14:27:18.432049+00		
171	project_devflow_gallery_4_caption	New template key	2026-04-28 14:27:18.432053+00	2026-04-28 14:27:18.432055+00		
172	project_devflow_gallery_4_image_alt	New template key	2026-04-28 14:27:18.432061+00	2026-04-28 14:27:18.432063+00		
173	project_devflow_gallery_4_image_url	New template key	2026-04-28 14:27:18.432067+00	2026-04-28 14:27:18.432069+00		
174	project_devflow_github_url	New template key	2026-04-28 14:27:18.432074+00	2026-04-28 14:27:18.432076+00		
175	project_devflow_hero_desc	New template key	2026-04-28 14:27:18.432081+00	2026-04-28 14:27:18.432083+00		
176	project_devflow_hero_title	New template key	2026-04-28 14:27:18.432087+00	2026-04-28 14:27:18.432089+00		
177	project_devflow_live_demo_url	New template key	2026-04-28 14:27:18.432094+00	2026-04-28 14:27:18.432096+00		
178	project_devflow_overview_text	New template key	2026-04-28 14:27:18.432101+00	2026-04-28 14:27:18.432103+00		
179	project_devflow_page_title	New template key	2026-04-28 14:27:18.432107+00	2026-04-28 14:27:18.432109+00		
180	project_devflow_stack_1	New template key	2026-04-28 14:27:18.432114+00	2026-04-28 14:27:18.432116+00		
181	project_devflow_stack_2	New template key	2026-04-28 14:27:18.43212+00	2026-04-28 14:27:18.432122+00		
182	project_devflow_stack_3	New template key	2026-04-28 14:27:18.432127+00	2026-04-28 14:27:18.432129+00		
183	project_devflow_stack_4	New template key	2026-04-28 14:27:18.432134+00	2026-04-28 14:27:18.432136+00		
184	project_devflow_stack_5	New template key	2026-04-28 14:27:18.43214+00	2026-04-28 14:27:18.432142+00		
185	project_devflow_status_label	New template key	2026-04-28 14:27:18.432147+00	2026-04-28 14:27:18.432149+00		
186	project_devflow_tech_desc	New template key	2026-04-28 14:27:18.432154+00	2026-04-28 14:27:18.432156+00		
187	project_devflow_thumb_image_alt	New template key	2026-04-28 14:27:18.43216+00	2026-04-28 14:27:18.432162+00		
188	project_devflow_thumb_image_url	New template key	2026-04-28 14:27:18.432167+00	2026-04-28 14:27:18.432169+00		
189	project_end_label	New template key	2026-04-28 14:27:18.432174+00	2026-04-28 14:27:18.432182+00		
190	project_features_heading	New template key	2026-04-28 14:27:18.432187+00	2026-04-28 14:27:18.432189+00		
191	project_gallery_heading	New template key	2026-04-28 14:27:18.432194+00	2026-04-28 14:27:18.432196+00		
192	project_github_label	New template key	2026-04-28 14:27:18.432201+00	2026-04-28 14:27:18.432203+00		
193	project_live_demo_label	New template key	2026-04-28 14:27:18.432207+00	2026-04-28 14:27:18.432209+00		
194	project_lumina_badge_1	New template key	2026-04-28 14:27:18.432214+00	2026-04-28 14:27:18.432216+00		
195	project_lumina_badge_2	New template key	2026-04-28 14:27:18.432221+00	2026-04-28 14:27:18.432223+00		
196	project_lumina_breadcrumb_label	New template key	2026-04-28 14:27:18.432233+00	2026-04-28 14:27:18.432235+00		
197	project_lumina_feature_1	New template key	2026-04-28 14:27:18.43224+00	2026-04-28 14:27:18.432242+00		
198	project_lumina_feature_2	New template key	2026-04-28 14:27:18.432247+00	2026-04-28 14:27:18.432248+00		
199	project_lumina_feature_3	New template key	2026-04-28 14:27:18.432253+00	2026-04-28 14:27:18.432255+00		
200	project_lumina_gallery_1_caption	New template key	2026-04-28 14:27:18.43226+00	2026-04-28 14:27:18.432262+00		
201	project_lumina_gallery_1_image_alt	New template key	2026-04-28 14:27:18.432266+00	2026-04-28 14:27:18.432268+00		
202	project_lumina_gallery_1_image_url	New template key	2026-04-28 14:27:18.432273+00	2026-04-28 14:27:18.432275+00		
203	project_lumina_gallery_2_caption	New template key	2026-04-28 14:27:18.43228+00	2026-04-28 14:27:18.432282+00		
204	project_lumina_gallery_2_image_alt	New template key	2026-04-28 14:27:18.432286+00	2026-04-28 14:27:18.432288+00		
205	project_lumina_gallery_2_image_url	New template key	2026-04-28 14:27:18.432293+00	2026-04-28 14:27:18.432295+00		
206	project_lumina_gallery_3_caption	New template key	2026-04-28 14:27:18.432304+00	2026-04-28 14:27:18.432306+00		
207	project_lumina_gallery_3_image_alt	New template key	2026-04-28 14:27:18.432311+00	2026-04-28 14:27:18.432313+00		
208	project_lumina_gallery_3_image_url	New template key	2026-04-28 14:27:18.432318+00	2026-04-28 14:27:18.43232+00		
209	project_lumina_gallery_4_caption	New template key	2026-04-28 14:27:18.432324+00	2026-04-28 14:27:18.432326+00		
210	project_lumina_gallery_4_image_alt	New template key	2026-04-28 14:27:18.432331+00	2026-04-28 14:27:18.432333+00		
211	project_lumina_gallery_4_image_url	New template key	2026-04-28 14:27:18.432338+00	2026-04-28 14:27:18.43234+00		
212	project_lumina_github_url	New template key	2026-04-28 14:27:18.432344+00	2026-04-28 14:27:18.432346+00		
213	project_lumina_hero_desc	New template key	2026-04-28 14:27:18.432351+00	2026-04-28 14:27:18.432353+00		
214	project_lumina_hero_title	New template key	2026-04-28 14:27:18.432358+00	2026-04-28 14:27:18.43236+00		
215	project_lumina_live_demo_url	New template key	2026-04-28 14:27:18.432364+00	2026-04-28 14:27:18.432366+00		
216	project_lumina_overview_text	New template key	2026-04-28 14:27:18.432371+00	2026-04-28 14:27:18.432373+00		
217	project_lumina_page_title	New template key	2026-04-28 14:27:18.432378+00	2026-04-28 14:27:18.432379+00		
218	project_lumina_stack_1	New template key	2026-04-28 14:27:18.432384+00	2026-04-28 14:27:18.432386+00		
219	project_lumina_stack_2	New template key	2026-04-28 14:27:18.432391+00	2026-04-28 14:27:18.432393+00		
220	project_lumina_stack_3	New template key	2026-04-28 14:27:18.432397+00	2026-04-28 14:27:18.432399+00		
221	project_lumina_stack_4	New template key	2026-04-28 14:27:18.432404+00	2026-04-28 14:27:18.432406+00		
222	project_lumina_stack_5	New template key	2026-04-28 14:27:18.432411+00	2026-04-28 14:27:18.432413+00		
223	project_lumina_status_label	New template key	2026-04-28 14:27:18.432418+00	2026-04-28 14:27:18.43242+00		
224	project_lumina_tech_desc	New template key	2026-04-28 14:27:18.432425+00	2026-04-28 14:27:18.432427+00		
225	project_lumina_thumb_image_alt	New template key	2026-04-28 14:27:18.432431+00	2026-04-28 14:27:18.432433+00		
226	project_lumina_thumb_image_url	New template key	2026-04-28 14:27:18.432438+00	2026-04-28 14:27:18.43244+00		
227	project_overview_heading	New template key	2026-04-28 14:27:18.432445+00	2026-04-28 14:27:18.432447+00		
228	project_tech_stack_heading	New template key	2026-04-28 14:27:18.432452+00	2026-04-28 14:27:18.432454+00		
229	projects_card_1_desc	New template key	2026-04-28 14:27:18.432458+00	2026-04-28 14:27:18.43246+00		
230	projects_card_1_github_url	New template key	2026-04-28 14:27:18.432465+00	2026-04-28 14:27:18.432467+00		
231	projects_card_1_image_alt	New template key	2026-04-28 14:27:18.432471+00	2026-04-28 14:27:18.432473+00		
232	projects_card_1_image_url	New template key	2026-04-28 14:27:18.432478+00	2026-04-28 14:27:18.43248+00		
233	projects_card_1_tag	New template key	2026-04-28 14:27:18.432485+00	2026-04-28 14:27:18.432487+00		
234	projects_card_1_title	New template key	2026-04-28 14:27:18.432493+00	2026-04-28 14:27:18.432495+00		
235	projects_card_2_desc	New template key	2026-04-28 14:27:18.432499+00	2026-04-28 14:27:18.432501+00		
236	projects_card_2_github_url	New template key	2026-04-28 14:27:18.432506+00	2026-04-28 14:27:18.432508+00		
237	projects_card_2_image_alt	New template key	2026-04-28 14:27:18.432512+00	2026-04-28 14:27:18.432514+00		
238	projects_card_2_image_url	New template key	2026-04-28 14:27:18.432523+00	2026-04-28 14:27:18.432525+00		
239	projects_card_2_tag	New template key	2026-04-28 14:27:18.43253+00	2026-04-28 14:27:18.432532+00		
240	projects_card_2_title	New template key	2026-04-28 14:27:18.432537+00	2026-04-28 14:27:18.432538+00		
241	projects_card_3_desc	New template key	2026-04-28 14:27:18.432543+00	2026-04-28 14:27:18.432546+00		
242	projects_card_3_github_url	New template key	2026-04-28 14:27:18.43255+00	2026-04-28 14:27:18.432552+00		
243	projects_card_3_image_alt	New template key	2026-04-28 14:27:18.432557+00	2026-04-28 14:27:18.432559+00		
244	projects_card_3_image_url	New template key	2026-04-28 14:27:18.432564+00	2026-04-28 14:27:18.432565+00		
245	projects_card_3_tag	New template key	2026-04-28 14:27:18.43257+00	2026-04-28 14:27:18.432572+00		
246	projects_card_3_title	New template key	2026-04-28 14:27:18.432577+00	2026-04-28 14:27:18.432579+00		
247	projects_card_4_desc	New template key	2026-04-28 14:27:18.432583+00	2026-04-28 14:27:18.432585+00		
248	projects_card_4_github_url	New template key	2026-04-28 14:27:18.43259+00	2026-04-28 14:27:18.432592+00		
249	projects_card_4_image_alt	New template key	2026-04-28 14:27:18.432596+00	2026-04-28 14:27:18.432598+00		
250	projects_card_4_image_url	New template key	2026-04-28 14:27:18.432603+00	2026-04-28 14:27:18.432605+00		
251	projects_card_4_tag	New template key	2026-04-28 14:27:18.432609+00	2026-04-28 14:27:18.432611+00		
252	projects_card_4_title	New template key	2026-04-28 14:27:18.432616+00	2026-04-28 14:27:18.432618+00		
253	projects_card_cta_github	New template key	2026-04-28 14:27:18.432622+00	2026-04-28 14:27:18.432624+00		
254	projects_card_cta_view	New template key	2026-04-28 14:27:18.432629+00	2026-04-28 14:27:18.432631+00		
255	projects_heading	New template key	2026-04-28 14:27:18.432636+00	2026-04-28 14:27:18.432637+00		
256	projects_page_title	New template key	2026-04-28 14:27:18.432642+00	2026-04-28 14:27:18.432644+00		
257	projects_subtitle	New template key	2026-04-28 14:27:18.432649+00	2026-04-28 14:27:18.432651+00		
258	site_brand_short	New template key	2026-04-28 14:27:18.432655+00	2026-04-28 14:27:18.432657+00		
259	site_cv_en_label	New template key	2026-04-28 14:27:18.432662+00	2026-04-28 14:27:18.432664+00		
260	site_cv_en_url	New template key	2026-04-28 14:27:18.432668+00	2026-04-28 14:27:18.43267+00		
261	site_cv_tr_label	New template key	2026-04-28 14:27:18.432675+00	2026-04-28 14:27:18.432677+00		
262	site_cv_tr_url	New template key	2026-04-28 14:27:18.432681+00	2026-04-28 14:27:18.432683+00		
263	site_footer_brand	New template key	2026-04-28 14:27:18.432697+00	2026-04-28 14:27:18.4327+00		
264	site_footer_copyright	New template key	2026-04-28 14:27:18.432705+00	2026-04-28 14:27:18.432707+00		
265	site_footer_github_url	New template key	2026-04-28 14:27:18.432712+00	2026-04-28 14:27:18.432714+00		
266	site_footer_linkedin_url	New template key	2026-04-28 14:27:18.432719+00	2026-04-28 14:27:18.432721+00		
267	site_nav_cv_label	New template key	2026-04-28 14:27:18.432725+00	2026-04-28 14:27:18.432727+00		
268	site_title	New template key	2026-04-28 14:27:18.432732+00	2026-04-28 14:27:18.432734+00		
\.


--
-- Data for Name: core_imagesetting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_imagesetting (id, name, description, file, created_date, updated_date) FROM stdin;
1	home_hero_profile_image	New template image key		2026-04-28 14:27:18.439989+00	2026-04-28 14:27:18.439996+00
\.


--
-- Data for Name: core_sitepreference; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_sitepreference (id, updated_date, created_date, default_journey_tab) FROM stdin;
1	2026-04-28 14:27:18.457757+00	2026-04-28 14:27:18.457765+00	education
\.


--
-- Data for Name: core_skill; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_skill (id, updated_date, created_date, "order", name, category) FROM stdin;
\.


--
-- Data for Name: core_socialmedia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_socialmedia (id, updated_date, created_date, "order", name, link, icon) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	generalsetting
8	core	imagesetting
9	core	skill
10	core	experience
11	core	education
12	core	socialmedia
13	core	document
14	core	sitepreference
15	contact	message
16	projects	project
17	projects	projectcategory
18	projects	projectsection
19	projects	projectlink
20	projects	projectimage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-28 14:27:18.182139+00
2	auth	0001_initial	2026-04-28 14:27:18.232167+00
3	admin	0001_initial	2026-04-28 14:27:18.244828+00
4	admin	0002_logentry_remove_auto_add	2026-04-28 14:27:18.248261+00
5	admin	0003_logentry_add_action_flag_choices	2026-04-28 14:27:18.251759+00
6	contenttypes	0002_remove_content_type_name	2026-04-28 14:27:18.265407+00
7	auth	0002_alter_permission_name_max_length	2026-04-28 14:27:18.272703+00
8	auth	0003_alter_user_email_max_length	2026-04-28 14:27:18.277907+00
9	auth	0004_alter_user_username_opts	2026-04-28 14:27:18.281433+00
10	auth	0005_alter_user_last_login_null	2026-04-28 14:27:18.285909+00
11	auth	0006_require_contenttypes_0002	2026-04-28 14:27:18.290027+00
12	auth	0007_alter_validators_add_error_messages	2026-04-28 14:27:18.29826+00
13	auth	0008_alter_user_username_max_length	2026-04-28 14:27:18.306564+00
14	auth	0009_alter_user_last_name_max_length	2026-04-28 14:27:18.310354+00
15	auth	0010_alter_group_name_max_length	2026-04-28 14:27:18.315818+00
16	auth	0011_update_proxy_permissions	2026-04-28 14:27:18.318623+00
17	auth	0012_alter_user_first_name_max_length	2026-04-28 14:27:18.321875+00
18	contact	0001_initial	2026-04-28 14:27:18.327287+00
19	contact	0002_generalsetting	2026-04-28 14:27:18.331882+00
20	contact	0003_remove_generalsetting_text_parameter_and_more	2026-04-28 14:27:18.336199+00
21	contact	0004_contactareainfo_delete_generalsetting	2026-04-28 14:27:18.342979+00
22	contact	0005_delete_contactareainfo	2026-04-28 14:27:18.346523+00
23	core	0001_initial	2026-04-28 14:27:18.357834+00
24	core	0002_rename_generalsettings_generalsetting	2026-04-28 14:27:18.364862+00
25	core	0003_alter_generalsetting_options_and_more	2026-04-28 14:27:18.372085+00
26	core	0004_imagesetting	2026-04-28 14:27:18.375954+00
27	core	0005_alter_imagesetting_options_imagesetting_created_date_and_more	2026-04-28 14:27:18.379808+00
28	core	0006_skill	2026-04-28 14:27:18.382721+00
29	core	0007_alter_skill_options	2026-04-28 14:27:18.383957+00
30	core	0008_alter_skill_percentage	2026-04-28 14:27:18.385319+00
31	core	0009_experience	2026-04-28 14:27:18.389029+00
32	core	0010_remove_experience_order	2026-04-28 14:27:18.390604+00
33	core	0011_alter_experience_job_title	2026-04-28 14:27:18.39539+00
34	core	0012_education	2026-04-28 14:27:18.401669+00
35	core	0013_socialmedia	2026-04-28 14:27:18.405208+00
36	core	0014_document	2026-04-28 14:27:18.409888+00
37	core	0015_alter_document_file_alter_imagesetting_file	2026-04-28 14:27:18.413278+00
38	core	0016_education_school_location_and_more	2026-04-28 14:27:18.416378+00
39	core	0017_skill_show_percentage	2026-04-28 14:27:18.418007+00
40	core	0018_reset_general_and_image_settings	2026-04-28 14:27:18.424799+00
41	core	0019_seed_new_template_keys	2026-04-28 14:27:18.440698+00
42	core	0020_remove_skill_percentage_remove_skill_show_percentage_and_more	2026-04-28 14:27:18.44666+00
43	core	0021_sitepreference	2026-04-28 14:27:18.459021+00
44	projects	0001_initial	2026-04-28 14:27:18.484857+00
45	sessions	0001_initial	2026-04-28 14:27:18.490622+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: projects_project; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects_project (id, title, slug, summary, cover_image, status, tech_stack, is_featured, "order", created_at, updated_at, category_id) FROM stdin;
\.


--
-- Data for Name: projects_projectcategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects_projectcategory (id, name, slug, icon) FROM stdin;
\.


--
-- Data for Name: projects_projectimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects_projectimage (id, image, image_type, alt_text, caption, "order", is_active, project_id) FROM stdin;
\.


--
-- Data for Name: projects_projectlink; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects_projectlink (id, label, url, icon, is_primary, "order", project_id) FROM stdin;
\.


--
-- Data for Name: projects_projectsection; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects_projectsection (id, section_type, title, content, data, "order", is_active, project_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: contact_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_message_id_seq', 1, false);


--
-- Name: core_document_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_document_id_seq', 1, false);


--
-- Name: core_education_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_education_id_seq', 1, false);


--
-- Name: core_experience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_experience_id_seq', 1, false);


--
-- Name: core_generalsettings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_generalsettings_id_seq', 268, true);


--
-- Name: core_imagesetting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_imagesetting_id_seq', 1, true);


--
-- Name: core_sitepreference_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_sitepreference_id_seq', 1, false);


--
-- Name: core_skill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_skill_id_seq', 1, false);


--
-- Name: core_socialmedia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_socialmedia_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 45, true);


--
-- Name: projects_project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_project_id_seq', 1, false);


--
-- Name: projects_projectcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_projectcategory_id_seq', 1, false);


--
-- Name: projects_projectimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_projectimage_id_seq', 1, false);


--
-- Name: projects_projectlink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_projectlink_id_seq', 1, false);


--
-- Name: projects_projectsection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_projectsection_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: contact_message contact_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact_message
    ADD CONSTRAINT contact_message_pkey PRIMARY KEY (id);


--
-- Name: core_document core_document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_document
    ADD CONSTRAINT core_document_pkey PRIMARY KEY (id);


--
-- Name: core_education core_education_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_education
    ADD CONSTRAINT core_education_pkey PRIMARY KEY (id);


--
-- Name: core_experience core_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_experience
    ADD CONSTRAINT core_experience_pkey PRIMARY KEY (id);


--
-- Name: core_generalsetting core_generalsettings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_generalsetting
    ADD CONSTRAINT core_generalsettings_pkey PRIMARY KEY (id);


--
-- Name: core_imagesetting core_imagesetting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_imagesetting
    ADD CONSTRAINT core_imagesetting_pkey PRIMARY KEY (id);


--
-- Name: core_sitepreference core_sitepreference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_sitepreference
    ADD CONSTRAINT core_sitepreference_pkey PRIMARY KEY (id);


--
-- Name: core_skill core_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_skill
    ADD CONSTRAINT core_skill_pkey PRIMARY KEY (id);


--
-- Name: core_socialmedia core_socialmedia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_socialmedia
    ADD CONSTRAINT core_socialmedia_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


--
-- Name: projects_project projects_project_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_slug_key UNIQUE (slug);


--
-- Name: projects_projectcategory projects_projectcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectcategory
    ADD CONSTRAINT projects_projectcategory_pkey PRIMARY KEY (id);


--
-- Name: projects_projectcategory projects_projectcategory_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectcategory
    ADD CONSTRAINT projects_projectcategory_slug_key UNIQUE (slug);


--
-- Name: projects_projectimage projects_projectimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectimage
    ADD CONSTRAINT projects_projectimage_pkey PRIMARY KEY (id);


--
-- Name: projects_projectlink projects_projectlink_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectlink
    ADD CONSTRAINT projects_projectlink_pkey PRIMARY KEY (id);


--
-- Name: projects_projectsection projects_projectsection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectsection
    ADD CONSTRAINT projects_projectsection_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_document_slug_9ffd5a20; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_slug_9ffd5a20 ON public.core_document USING btree (slug);


--
-- Name: core_document_slug_9ffd5a20_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_slug_9ffd5a20_like ON public.core_document USING btree (slug varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: projects_project_category_id_708edb98; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_project_category_id_708edb98 ON public.projects_project USING btree (category_id);


--
-- Name: projects_project_slug_2d50067a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_project_slug_2d50067a_like ON public.projects_project USING btree (slug varchar_pattern_ops);


--
-- Name: projects_projectcategory_slug_d9c111cf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_projectcategory_slug_d9c111cf_like ON public.projects_projectcategory USING btree (slug varchar_pattern_ops);


--
-- Name: projects_projectimage_project_id_618ded0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_projectimage_project_id_618ded0e ON public.projects_projectimage USING btree (project_id);


--
-- Name: projects_projectlink_project_id_929ddb4c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_projectlink_project_id_929ddb4c ON public.projects_projectlink USING btree (project_id);


--
-- Name: projects_projectsection_project_id_90afa054; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_projectsection_project_id_90afa054 ON public.projects_projectsection USING btree (project_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_category_id_708edb98_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_category_id_708edb98_fk_projects_ FOREIGN KEY (category_id) REFERENCES public.projects_projectcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_projectimage projects_projectimag_project_id_618ded0e_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectimage
    ADD CONSTRAINT projects_projectimag_project_id_618ded0e_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_projectlink projects_projectlink_project_id_929ddb4c_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectlink
    ADD CONSTRAINT projects_projectlink_project_id_929ddb4c_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_projectsection projects_projectsect_project_id_90afa054_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects_projectsection
    ADD CONSTRAINT projects_projectsect_project_id_90afa054_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict ZHBnKIHMMil16fxihDW73YqC4lddhYwuF8BM26YeRt60mUbejgjjuT3HTIUUfNb

