upstream portfolio_app {
    server 127.0.0.1:8000;
}

server {
    listen 172.31.39.20:80;
    server_name 13.61.100.110 172.31.39.20;

    return 301 https://keremboylu.com.tr$request_uri;
}

server {
    listen 172.31.39.20:80;
    server_name keremboylu.com.tr www.keremboylu.com.tr;

    return 301 https://$host$request_uri;
}

server {
    listen 172.31.39.20:443 ssl;
    server_name keremboylu.com.tr www.keremboylu.com.tr;
    server_tokens off;
    client_max_body_size 15M;
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        proxy_pass http://portfolio_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}

server {
    listen 172.31.39.20:80;
    server_name admin.keremboylu.com.tr;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}

server {
    listen 172.31.39.20:443 ssl;
    server_name admin.keremboylu.com.tr;
    server_tokens off;
    client_max_body_size 15M;
    ssl_certificate /etc/letsencrypt/live/admin.keremboylu.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.keremboylu.com.tr/privkey.pem;

    location / {
        proxy_pass http://portfolio_app/__not-found__/;
        proxy_set_header Host keremboylu.com.tr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}

server {
    listen 100.118.32.110:443 ssl;
    server_name admin.keremboylu.com.tr;
    server_tokens off;
    client_max_body_size 50M;
    ssl_certificate /etc/letsencrypt/live/admin.keremboylu.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.keremboylu.com.tr/privkey.pem;

    location / {
        proxy_pass http://portfolio_app;
        proxy_set_header Host admin.keremboylu.com.tr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}
